### PR TITLE
Add new tests

### PR DESCRIPTION
**Pull request by connorphee**
Added new tests to check that these elements in the modal exist:

- Title (data-launchy-title)
- Text Content (data-launchy-text)
- Dialog/Modal (#launchy-dialog-)
- OK and 'x' buttons (#launchy-close-control-, data-launchy-close)

I haven't worked with Jasmine before, so I spent some time looking over those Docs, but I am still looking to find a way to verify the focus of the modal on launch, as well as on different events. I think those tests would be very valuable.

If these are not what you are looking for please let me know and I will make changes. As I mentioned above I will continue working to expand the suite of tests! Thanks again for the opportunity to help!

### CODE REVIEW

**Comment by svinkle** [comment]
@connorphee These are exactly what I'm looking for! Thanks so much for your contribution. 👍

Absolutely there's more that can be tested. I'm curious now, is there a way to test which element currently has focus? And yes, event tests would be ideal as well.

This is a great start though. If you're game, feel free to add some more! Much appreciated. 🙂

**Comment by connorphee** [comment]
No problem! 

I know that [document.activeElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement) can be used, but the hard part for me is replicating the modal being launched in a test. As I mentioned I am new to Jasmine so I am still exploring, but if you know of any ways to mock events, it would definitely get me going for writing more. If not, I will continue to explore and see what I can do!

Thanks again for the opportunity to contribute!

**Comment by svinkle** [comment]
So, I just thought about event triggering and remembered that DOM elements have a `click()` method. Just tried this and it totally works:
```javascript
it('with `launchy-dialog-0` container to have focus', (done) => {
    setTimeout(() => {
        fixture.el.querySelector('#launchy-control-0').click();
        expect(fixture.el.querySelector('#launchy-dialog-0')).toEqual(document.activeElement);
    }, 500);
    done();
});
```
That should get you started for exploring other tests to write. 🙂

**Comment by connorphee** [comment]
I hate to admit it but I actually came across this and for some reason I thought it was exclusive to jQuery and thought "Wow that would be nice to have". 

Thanks for picking up my slack, that will definitely keep me going!

**Comment by svinkle** [comment]
Actually so did I the first time I saw it! Then was stoked to find it's actually a vanilla JS feature. 😅

**Comment by connorphee** [comment]
Yeah that is a really nice feature for the platform to have! It definitely opens some doors!

**Pull request merged**
